connector.name=paimon

warehouse=s3://aia/warehouse/paimon/aia
# S3 配置
fs.native-s3.enabled=true
s3.endpoint=http://192.168.240.77:9005
s3.path-style-access=true
# s3.access-key=admin
# s3.secret-key=Command_123
s3.aws-access-key=admin
s3.aws-secret-key=Command_123
s3.region=us-east-1
# 禁用 HDFS (使用 S3 时不需要 HDFS)
fs.hadoop.enabled=false